# Generated by Django 4.0.5 on 2022-06-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_topic_slug_alter_topic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.topic'),
        ),
    ]
