# Generated by Django 4.0.5 on 2022-06-16 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_thread_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='down',
            new_name='upvotes',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='down',
            new_name='upvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='likes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comment')),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
