# Generated by Django 4.0.5 on 2022-06-19 20:27

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=markdownx.models.MarkdownxField(max_length=5000),
        ),
    ]
