# Generated by Django 3.2.13 on 2022-06-20 13:55

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_thread_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='main/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, upload_to='main/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=markdownx.models.MarkdownxField(max_length=5000),
        ),
    ]
