# Generated by Django 3.2.13 on 2022-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220620_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='upvotes',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
